models:
    llm: "gpt-4o-mini"
inference:
    verbose: False
    modality: 'text'
    data: 'test_filled_questions.json'
    num_samples: -1
    geometry: 'square'
    radius: 64
    output_dir: 'output/'
    question_path: 'output/qa_data.csv'
    save_output_response: True